#
# This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
#

#
# To use this client, jsonrpc_pyclient must be installed:
# pip install jsonrpc_pyclient
#

from jsonrpc_pyclient import client

class jsonrpc_client(client.Client):
    def __init__(self, connector, version='2.0'):
        super(jsonrpc_client, self).__init__(connector, version)

    def add(self, a, b):
        parameters = {}
        parameters['a'] = a
        parameters['b'] = b

        result = self.call_method('add', parameters)
        return result

    def echo(self, message):
        parameters = {}
        parameters['message'] = message

        result = self.call_method('echo', parameters)
        return result

    def get_val(self):
        parameters = None

        result = self.call_method('get_val', parameters)
        return result

    def mult(self, a, b):
        parameters = {}
        parameters['a'] = a
        parameters['b'] = b

        result = self.call_method('mult', parameters)
        return result

    def set_val(self, value):
        parameters = {}
        parameters['value'] = value

        result = self.call_method('set_val', parameters)
        return result


